### ISSUE TITLE
Explain differences from proxy driver

### ISSUE THREAD

**Issue by coderanger** [neillturner/kitchen-ssh#10]
The `ssh` driver is mostly overlapping with the `proxy` driver included in TK itself. We get a fair amount of user confusion about this. Could you maybe add a note to your docs about the specific cases where this should be used (such as the `gzip` sub-driver)?

**Comment by neillturner** [comment]
For a bit of history this kitchen ssh driver was originally written  so that server created  separately (in my case EC2 instances created by cloud formation) could have repeated run of test kitchen provisioner. 
I also added gzip support to massively speed up the time it took to copy all the config files to the instance. 
Since writing this so other solutions how been written. There is a proxy driver in test-kitchen  that proxies commands through to a test instance whose lifecycle is not managed by Test Kitchen.     
Also kitchen-sync plugin has been written that also massively improves performance but by just sync the changes to config files instead of zipping them up
